### ISSUE TITLE
页面一共有 0 个未进行的任务

### ISSUE THREAD

**Issue by chu-han** [ZCY01/jdtry#19]
create Iframe for 打开请求/activity/getActivityList 页面 返回{"bottom":null}。新增一个标签页同样地址和参数却不会。iframe 打开方式，被JD服务端屏蔽了吗？

**Comment by ZCY01** [comment]
建议清理缓存，我也碰到过，但是没有解决方案。

**Comment by chu-han** [comment]
> 建议清理缓存，我也碰到过，但是没有解决方案。

好的，谢谢。我试下。
