### ISSUE TITLE
大佬能不能添加一个清空商品列表的功能呢？

### ISSUE THREAD

**Issue by caomei4321** [ZCY01/jdtry#3]

**Comment by ZCY01** [comment]
可以啊。

**Comment by kate09280774** [comment]
大佬。这个京东试用还能用吗？怎么安装依赖呀。我下载了整个文件包。扩展无法安装呀

**Comment by ZCY01** [comment]
> 大佬。这个京东试用还能用吗？怎么安装依赖呀。我下载了整个文件包。扩展无法安装呀

参考
https://jingyan.baidu.com/article/7f766daf63f7bb0000e1d03f.html
