### ISSUE TITLE
商品列表无法滚动

### ISSUE THREAD

**Issue by git1848** [ZCY01/jdtry#5]
BUG？
商品列表无法滚动，没有出现滚动条
系统：mac
浏览器：Edge Version 80.0.361.103 (Official build) (64-bit)

**Comment by ZCY01** [comment]
是最新版本吗，之前版本如果使用过搜索功能的确会出现无法滚动的现象，已经修复了。

**Comment by git1848** [comment]
@ZCY01 
都没有出现滚动条，也无法滚动

不搜索的情况下：
![WX20200529-093221](https://user-images.githubusercontent.com/3184124/83211364-84e1b080-a18f-11ea-8676-cfa2b0aa047f.png)

搜索的情况下：
![WX20200529-09330402](https://user-images.githubusercontent.com/3184124/83211374-89a66480-a18f-11ea-84f3-f9ec008f1f6f.png)

**Comment by ZCY01** [comment]
应该是浏览器适配 没有出现滚动条 的原因。我测试一下。可以先用 Chrome

**Comment by ZCY01** [comment]
我下载了 Microsoft Edge Version 81.0.416.77 (Official build) (64-bit) 可以滚动，无法复现这个bug.
