### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by jiutianjuju** [ZCY01/jdtry#6]
chrome版本 76.0.3809.87

插件详情页有这个报错
![image](https://user-images.githubusercontent.com/40514186/85942823-6291ad00-b95e-11ea-818d-e0256c55c7d2.png)

**Comment by ZCY01** [comment]
是自己编译的还是下载 release 版本？

**Comment by ZCY01** [comment]
我在 chrome  76.0.3809.132  尝试 release 和重新编译的版本，都没有复现。😓

**Comment by jiutianjuju** [comment]
release 版本，我的操作问题。。我下载的crx底下的压缩包，把crx文件解压可以用
