### ISSUE TITLE
在插件使用过程中遇到的问题

### ISSUE THREAD

**Issue by jiutianjuju** [ZCY01/jdtry#7]
1.五个任务设置同时运行，跑完搜索其它任务没有运行
2.成功列表没有获取到数据
3.定时任务只能设置为整点运行

**Comment by ZCY01** [comment]
1. 麻烦附上运行记录
![image](https://user-images.githubusercontent.com/15939669/85980847-ba3f1f80-ba15-11ea-9eb0-1da94ffc1f3a.png)
![image](https://user-images.githubusercontent.com/15939669/85980859-bdd2a680-ba15-11ea-944d-b85dbc830ff3.png)
2. 成功列表设定的是，只显示可领取的列表。过期或者已领取都不显示。
3. 。。。

**Comment by jiutianjuju** [comment]
搜索任务运行了之后运行的申请，取关任务没有跑，我在console看了也没有报错

**Comment by jiutianjuju** [comment]
![image](https://user-images.githubusercontent.com/40514186/86100383-538c3580-baeb-11ea-91b7-3c6b184ed539.png)

**Comment by ZCY01** [comment]
噢。取关我做了一个小 trick。模拟正常用户的行为。
只有关注量达到了 250 个以上才做清理。
